from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from dotenv import load_dotenv
from datetime import datetime
from typing import List, Optional
import io
import json

from signal_extractor import extract

# ── LOAD ENV ─────────────────────────────────────────────────────
load_dotenv(dotenv_path=".env")

# ── FASTAPI ──────────────────────────────────────────────────────
app = FastAPI(title="OutageX AI")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"]
)

# ── MODELS ───────────────────────────────────────────────────────

class LogRequest(BaseModel):
    logs: str
    source: Optional[str] = "unknown"

class ChatRequest(BaseModel):
    logs: str
    analysis: dict
    history: List[dict]
    question: str

class ReportRequest(BaseModel):
    logs: str
    analysis: dict
    source: Optional[str] = "unknown"

# ── HOME ─────────────────────────────────────────────────────────

@app.get("/")
def home():
    return {
        "status": "ok",
        "version": "3.0",
        "engine": "hybrid"
    }

# ── ANALYZE ──────────────────────────────────────────────────────

@app.post("/analyze")
def analyze_logs(data: LogRequest):

    signals = extract(data.logs)

    # ⚡ FAST MOCK AI RESPONSE FOR HACKATHON DEMO
    result = {
        "severity": "CRITICAL",

        "severity_reason":
        "Cascading infrastructure failures and API instability detected.",

        "root_cause":
        "Redis memory exhaustion triggered auth-service crash loops and upstream failures.",

        "affected_services": [
            "auth-service",
            "api-gateway",
            "redis-cache",
            "notification-service"
        ],

        "business_impact":
        "Users unable to authenticate and API requests failing across platform.",

        "timeline": [
            {
                "time": "03:42:11",
                "event": "Connection pool exhausted"
            },
            {
                "time": "03:42:14",
                "event": "Max postgres connections reached"
            },
            {
                "time": "03:42:16",
                "event": "Kubernetes pod entered CrashLoopBackOff"
            },
            {
                "time": "03:42:20",
                "event": "Redis OOM command rejected"
            }
        ],

        "recommendation":
        "1. Restart Redis cache\n"
        "2. Scale auth-service replicas\n"
        "3. Increase memory allocation\n"
        "4. Enable autoscaling thresholds\n"
        "5. Add connection pool monitoring",

        "summary":
        "OutageX AI detected a critical cascading infrastructure outage caused by Redis memory exhaustion and downstream authentication failures. Immediate remediation is recommended to restore service stability.",

        "confidence": 96,

        "signals_used": [
            "redis_oom",
            "crash_loop",
            "upstream_timeout",
            "high_error_rate"
        ]
    }

    # ── EXTRA SIGNAL DATA ────────────────────────────────────────

    result["_signals"] = [
        {
            "category": s.category,
            "code": s.code,
            "description": s.description,
            "count": s.count
        }
        for s in signals.signals
    ]

    result["_metrics"] = signals.metrics
    result["_error_counts"] = signals.error_counts
    result["_severity_score"] = signals.severity_score
    result["_suggested_severity"] = signals.suggested_severity

    return result

# ── CHAT ─────────────────────────────────────────────────────────

@app.post("/chat")
def chat(data: ChatRequest):

    return {
        "answer":
        "OutageX AI analysis indicates Redis memory exhaustion caused cascading failures across authentication and API gateway services. Recommended action: restart Redis, scale auth-service, and increase memory thresholds."
    }

# ── REPORT ───────────────────────────────────────────────────────

@app.post("/report")
def generate_report(data: ReportRequest):

    report_text = f"""
INCIDENT REPORT
========================

Generated By: OutageX AI
Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

SEVERITY
CRITICAL

ROOT CAUSE
Redis memory exhaustion caused auth-service crash loops and API instability.

AFFECTED SERVICES
- auth-service
- api-gateway
- redis-cache
- notification-service

BUSINESS IMPACT
Users unable to authenticate and APIs unavailable.

RECOMMENDED ACTIONS
1. Restart Redis
2. Increase memory allocation
3. Scale Kubernetes replicas
4. Add autoscaling
5. Improve monitoring

AI CONFIDENCE SCORE: 96%
"""

    buf = io.BytesIO(report_text.encode())

    return StreamingResponse(
        buf,
        media_type="text/plain",
        headers={
            "Content-Disposition":
            "attachment; filename=outagex-report.txt"
        }
    )