from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import anthropic, json, re, io
from datetime import datetime
from typing import List, Optional
from signal_extractor import extract   # ← Hybrid layer

app = FastAPI(title="OutageX AI")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])
client = anthropic.Anthropic()

# ── Prompts ──────────────────────────────────────────────────────────────────

ANALYZE_SYSTEM = """You are OutageX AI — an expert autonomous SRE incident analyzer.
You receive both raw logs AND pre-extracted signals from a deterministic analysis engine.
Your job is to reason OVER those signals, confirm or refine them, and produce the final structured analysis.
Trust the pre-extracted signals as hard facts; add your reasoning and deeper context.

Return ONLY valid JSON — no markdown, no extra text:
{
  "severity": "LOW"|"MEDIUM"|"HIGH"|"CRITICAL",
  "severity_reason": "one sentence explaining severity",
  "root_cause": "precise one-sentence root cause",
  "affected_services": ["svc1", "svc2"],
  "business_impact": "user/revenue impact in one sentence",
  "timeline": [{"time": "HH:MM:SS", "event": "what happened"}],
  "recommendation": "1. action\\n2. action\\n3. action",
  "summary": "2-3 sentence executive summary for a CTO",
  "confidence": 88,
  "signals_used": ["signal_code_1", "signal_code_2"]
}"""

CHAT_SYSTEM = """You are OutageX AI, an expert SRE assistant.
You have the full log analysis and the raw logs. Answer follow-up questions technically and concisely.
Use plain text only — no markdown."""

REPORT_SYSTEM = """You are OutageX AI. Write a professional SRE post-mortem report in plain text.

Use EXACTLY this structure:
INCIDENT REPORT
===============
Date/Time: [extract from logs or use now]
Severity: [severity]
Platform: OutageX AI Autonomous Incident Intelligence

EXECUTIVE SUMMARY
[2-3 sentences for a VP/CTO audience]

ROOT CAUSE ANALYSIS
[technical explanation with reasoning]

TIMELINE OF EVENTS
1. HH:MM - event
2. HH:MM - event
[continue]

AFFECTED SERVICES & BUSINESS IMPACT
[services and revenue/user impact]

SIGNALS DETECTED
[list key signals the engine found]

RECOMMENDED REMEDIATION STEPS
1. [immediate action]
2. [short-term fix]
3. [longer-term fix]

PREVENTION RECOMMENDATIONS
1. [architectural improvement]
2. [monitoring improvement]
3. [process improvement]

AI CONFIDENCE SCORE: [X]%
Report generated by OutageX AI Platform"""


# ── Models ───────────────────────────────────────────────────────────────────
class LogRequest(BaseModel):
    logs: str
    source: Optional[str] = "unknown"

class ChatRequest(BaseModel):
    logs: str
    analysis: dict
    history: List[dict]
    question: str

class ReportRequest(BaseModel):
    logs: str
    analysis: dict
    source: Optional[str] = "unknown"


# ── Routes ───────────────────────────────────────────────────────────────────
@app.get("/")
def home():
    return {"status": "ok", "version": "3.0", "engine": "hybrid"}


@app.post("/analyze")
def analyze_logs(data: LogRequest):
    # ── STEP 1: Deterministic signal extraction ──
    signals = extract(data.logs)

    # ── STEP 2: Build enriched prompt ──
    enriched_prompt = f"""Source: {data.source}

{signals.summary_context}

Raw logs:
{data.logs}

Pre-detected services: {', '.join(signals.affected_services) or 'none detected'}
Error counts: {json.dumps(signals.error_counts)}
Extracted metrics: {json.dumps(signals.metrics)}

Now produce the final JSON analysis, refining the above signals with your reasoning."""

    # ── STEP 3: LLM reasoning over signals ──
    msg = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=1200,
        system=ANALYZE_SYSTEM,
        messages=[{"role": "user", "content": enriched_prompt}]
    )
    raw = msg.content[0].text.strip()
    raw = re.sub(r"^```json|^```|```$", "", raw, flags=re.MULTILINE).strip()
    result = json.loads(raw)

    # ── STEP 4: Attach signal metadata to response ──
    result["_signals"] = [
        {"category": s.category, "code": s.code, "description": s.description, "count": s.count}
        for s in signals.signals
    ]
    result["_metrics"] = signals.metrics
    result["_error_counts"] = signals.error_counts
    result["_severity_score"] = signals.severity_score
    result["_suggested_severity"] = signals.suggested_severity

    return result


@app.post("/chat")
def chat(data: ChatRequest):
    context = f"Logs:\n{data.logs}\n\nAnalysis:\n{json.dumps(data.analysis, indent=2)}"
    messages = [
        {"role": "user", "content": context + "\n\nReady for follow-up questions."},
        {"role": "assistant", "content": "Understood. I have full incident context. Ask me anything."},
    ]
    for m in data.history:
        messages.append({"role": m["role"], "content": m["content"]})
    messages.append({"role": "user", "content": data.question})
    msg = client.messages.create(
        model="claude-opus-4-5", max_tokens=600,
        system=CHAT_SYSTEM, messages=messages
    )
    return {"answer": msg.content[0].text.strip()}


@app.post("/report")
def generate_report(data: ReportRequest):
    prompt = f"""Source: {data.source}
Logs:
{data.logs}

Analysis:
{json.dumps(data.analysis, indent=2)}

Generate the full post-mortem report now."""

    msg = client.messages.create(
        model="claude-opus-4-5", max_tokens=1500,
        system=REPORT_SYSTEM,
        messages=[{"role": "user", "content": prompt}]
    )
    report_text = msg.content[0].text.strip()

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.styles import ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4,
            leftMargin=2.2*cm, rightMargin=2.2*cm, topMargin=2*cm, bottomMargin=2*cm)

        title_s  = ParagraphStyle("t",  fontSize=17, fontName="Helvetica-Bold", textColor=colors.HexColor("#ef4444"), spaceAfter=4)
        meta_s   = ParagraphStyle("m",  fontSize=8,  fontName="Helvetica",      textColor=colors.HexColor("#888888"), spaceAfter=14)
        head_s   = ParagraphStyle("h",  fontSize=11, fontName="Helvetica-Bold", textColor=colors.HexColor("#1a1a2e"), spaceBefore=14, spaceAfter=4)
        body_s   = ParagraphStyle("b",  fontSize=9,  fontName="Helvetica",      leading=14, textColor=colors.HexColor("#333"))

        def esc(t): return t.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")

        story = [
            Paragraph("⚡ OutageX AI — Incident Post-Mortem Report", title_s),
            Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  |  Source: {data.source.upper()}  |  Engine: Hybrid AI v3", meta_s),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor("#ef4444"), spaceAfter=8),
        ]
        for line in report_text.split("\n"):
            line = line.strip()
            if not line: story.append(Spacer(1, 5))
            elif line.startswith("===") or line.startswith("---"): continue
            elif line.isupper() and len(line) > 4: story.append(Paragraph(esc(line), head_s))
            else: story.append(Paragraph(esc(line), body_s))

        doc.build(story)
        buf.seek(0)
        return StreamingResponse(buf, media_type="application/pdf",
            headers={"Content-Disposition": "attachment; filename=outagex-report.pdf"})
    except ImportError:
        buf = io.BytesIO(report_text.encode())
        return StreamingResponse(buf, media_type="text/plain",
            headers={"Content-Disposition": "attachment; filename=outagex-report.txt"})
